#!/usr/bin/env bash
# This script changes localhost and facebook.com IP resolution in /etc/hosts

sudo sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
